version: "3.6"

services:
  nginx:
    image: nginx:1.23
    restart: on-failure
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./config/docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./var/log/nginx:/var/log/nginx
    depends_on:
      - php
  php:
    build: ./config/docker/php
    restart: on-failure
    volumes:
      - .:/var/www/html