version: "3.6"

services:
  nginx:
    image: nginx:1.23
    restart: on-failure
    ports:
      - "80:80"
    volumes:
      - .:/app
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./var/log/nginx:/var/log/nginx